### ISSUE TITLE
[Candidate 3v3 Subjugation Mk 14 [WBC Winner]] At least one AI is not collecting from main supply

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#107]
**Issue Description**
At least one AI is not collecting from main supply.

**Expected behavior**
All AI collect money from supplies.

**Screenshots**
![shot_20210327_122659_10](https://user-images.githubusercontent.com/4720891/112719179-d960d400-8ef7-11eb-97f8-f3132a90cce7.jpg)

**Comment by kABUSE1** [comment]
This took quite some time to fix without changing the base layout.

Still not a good AI but at least working and collecting cash. It doesn't get much better without a full make-over.

The only noticeable difference for the user is that the two middle bases now have a 45° rotated supply, instead of 0°.

[Subjugation Mk 14 [WBC Winner].zip](https://github.com/xezon/GeneralsRankedMaps/files/6370478/Subjugation.Mk.14.WBC.Winner.zip)

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/354b483148cdc34e48eafa1f437cf5f6f92213c6
