### ISSUE TITLE
[Candidate 1v1 [RANK] Final Crossroad ZH v2] Terrain textures are not blended

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#151]
**Issue Description**
Terrain textures are not blended.

**Expected behavior**
Terrain textures are blended beautifully to appear natural.

**Screenshots**
![shot_20210411_171437_15](https://user-images.githubusercontent.com/4720891/114310053-ac144880-9ae9-11eb-88bd-6c2e32b0d359.jpg)
![shot_20210411_171442_16](https://user-images.githubusercontent.com/4720891/114310054-ad457580-9ae9-11eb-81b9-fe4c3f73df24.jpg)

**Comment by Jundiyy** [comment]
I will let the mapper know.

**Comment by Jundiyy** [comment]
Mapper has given permission to allow me or someone to texture for him. TKLyo said he will try and do it.

**Comment by Jundiyy** [comment]
Fixed in #37 
@TKLyo
The 2 middle docks look borderline pass, the ground below them is not flat, thus raising a corner off the ground for each.
I see you have balanced the wooden huts near the bases, I would revert this a bit for 2 reasons, if you look carefully, the mound below them is not the same, (I have not tested this but) this could allow for one to shoot over the mound and not the other, please test, otherwise revert the pos so both are on the mounds or flatten the areas a bit. Second reason is the hp, please revert the health, back to 100% or give it enough health to be garrisoned,

**Comment by TKLyo** [comment]
I'll test it out later on. @Jundiyy Might make the changes later if I see any problems with it

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/246e6ce1d0154ece99aeb2c6260d4f7d1c961996
