### ISSUE TITLE
[Candidate 3v3 Subjugation Mk 14 [WBC Winner]] Yellow particles are not nice to watch

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#40]
**Issue Description**
Flying yellow dots are visible on the map.

**Expected behavior**
There should be no yellow dots flying.

**Screenshots**
![shot_20210327_122338_7](https://user-images.githubusercontent.com/4720891/112719138-97379280-8ef7-11eb-9a2b-47d4f196779a.jpg)

**Comment by kABUSE1** [comment]
The yellow dots are supposed to be fireflies. It's a cute idea.

The issue is that they don't look like fireflies because they are way too high above the ground, which is noticeable as you move the cam around. The number could be greatly reduced to make it less apparent. Will that suffice or do you want them fully removed?

Maybe you should test some different map.ini values:
  SnowBoxDensity = 0.1       	;amount of snow particles per world-unit. Raise to increase particle count.

**Comment by xezon** [comment]
I think the safest approach is removal.

**Comment by kABUSE1** [comment]
Removed.

[Subjugation Mk 14 [WBC Winner].zip](https://github.com/xezon/GeneralsRankedMaps/files/6370480/Subjugation.Mk.14.WBC.Winner.zip)

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/354b483148cdc34e48eafa1f437cf5f6f92213c6
